<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>post_latest_about</name>
   <tag></tag>
   <elementGuidId>9c6d1b40-0ae1-4f95-ae81-30105ef6e6d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@class='content']/article[@class='post'][1]/header/div/div[contains(@class,'about')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
